[package]
name = "template-compiler"
description = "A compiler from a simple template language to Wasm components"
keywords = ["compiler", "webassembly", "wasm"]
categories = ["compilers", "parser-implementations", "template-engine", "wasm"]
repository = "https://github.com/esoterra/template-compiler"
readme = "README.md"
license = "MIT OR Apache-2.0"

version = "0.1.2"
edition = "2024"
authors = ["Robin Brown"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chumsky = "0.12.0"
clap = { version = "4.0", features = ["derive"] }
wasm-encoder = "0.245"
wat = "1.245"
wit-parser = "0.245"

[dev-dependencies]
wasmprinter = "0.245"
wasmtime = "42"
pretty_assertions = "1.1.0"
